# comment
[root]
array = ["string",true,false]
# braces = {}
integer = -100
float = 3.14
boolean = true

[root.table]
array = ["string",100,1.3,true,["nested",4.3,false]]
integer = 4

[root.table.cable.stable]
boolean = true
